library(dplyr)
library(tidyr)
choronsData <- read.csv('data/chronos.csv', stringsAsFactors = F, sep=',', header = T)
cnData <- read.csv('data/cn.csv', stringsAsFactors = F, sep=",", header = T)
expressionData <- read.csv('data/expression.csv', stringsAsFactors = F, sep=',', header = T)
metaData <- read.csv('data/metadata.csv', stringsAsFactors = F, sep=',', header = T)
allDF <- inner_join(expressionData, cnData, by='Sample_ID')
allDF <- inner_join(allDF, choronsData, by='Sample_ID')
allDF <- inner_join(allDF, metaData, by='Sample_ID')
